services:
  scheduler:
    image: ghcr.io/arkasy/scheduler:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/app/log
      - ./schedule.yml:/app/schedule.yml
    environment:
      TZ: Europe/Paris
